const LABELS={0: 'beetroot',
 1: 'bell pepper',
 2: 'cabbage',
 3: 'capsicum',
 4: 'carrot',
 5: 'cauliflower',
 6: 'chilli pepper',
 7: 'corn',
 8: 'cucumber',
 9: 'eggplant',
 10: 'garlic',
 11: 'ginger',
 12: 'jalepeno',
 13: 'lemon',
 14: 'lettuce',
 15: 'onion',
 16: 'paprika',
 17: 'peas',
 18: 'potato',
 19: 'raddish',
 20: 'soy beans',
 21: 'spinach',
 22: 'sweetcorn',
 23: 'sweetpotato',
 24: 'tomato',
 25: 'turnip'}